endpoints:
  content_packages: 'https://capi.9c9media.com/destinations/{platform_type}/platforms/desktop/contents/{title_id}/contentPackages'
  manifest: 'https://capi.9c9media.com/destinations/{platform_type}/platforms/desktop/playback/contents/{title_id}/contentPackages/{package_id}/manifest.pmpd'
  license: 'https://license.9c9media.ca/playready'
